#!/usr/bin/env python3
"""
Embed the web UI into a C source file.

    python3 embed_ui.py ui build/ui_html.h

Emitting the HTML as a C array keeps tts_server.exe a single self-contained
file: no data folder to lose, and nothing to get out of step with the binary.
Index.html and app.js are kept as real files so they stay editable and
lintable.
"""

import os
import sys


def emit(path, name):
    with open(path, "rb") as fh:
        data = fh.read()
    lines = []
    lines.append("/* Generated from %s by embed_ui.py - do not edit. */\n"
                 % os.path.basename(path))
    lines.append("static const char %s[] = {\n" % name)
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",\n")
    lines.append("    0x00\n};\n")
    return "".join(lines), len(data)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    srcdir, out = sys.argv[1:3]

    parts = []
    lengths = []
    for fname, sym in (("index.html", "win7_tts_ui_html"),
                       ("app.js", "win7_tts_ui_app_js")):
        path = os.path.join(srcdir, fname)
        text, n = emit(path, sym)
        parts.append(text)
        lengths.append((sym, n))

    with open(out, "w", encoding="ascii") as fh:
        fh.write("/* Generated by embed_ui.py - do not edit by hand. */\n")
        fh.write("#ifndef UI_HTML_H\n#define UI_HTML_H\n\n")
        for text in parts:
            fh.write(text)
        for sym, n in lengths:
            fh.write("static const unsigned long %s_len = %dUL;\n" % (sym, n))
        fh.write("#endif /* UI_HTML_H */\n")

    print("embedded %d bytes of UI into %s"
          % (sum(n for _, n in lengths), out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
