#!/usr/bin/env python3
"""
Generate the thunk table, resolver table and .def file for the Win7 shim DLL.

Why this exists
---------------
The official sherpa-onnx Windows binaries are compiled with a Windows 10 SDK, so
they statically import functions that do not exist on Windows 7, e.g.
GetSystemTimePreciseAsFileTime, CreateFile2, InitializeCriticalSectionEx,
GetProcessMitigationPolicy, Fls*, the CONDITION_VARIABLE family, PathCchRemove*
and CreateDXGIFactory2.  On Windows 7 the loader aborts the process before any
code runs:

    The procedure entry point XXX could not be located in the dynamic library
    KERNEL32.dll

You cannot add an export to the real KERNEL32.dll, so the fix is to redirect the
imports into a shim DLL of our own.  patch_pe.py rewrites the import descriptors
so that every import coming from KERNEL32.dll, api-ms-win-core-path-l1-1-0.dll
or dxgi.dll resolves against the shim instead.  The shim exports every one of
those functions and, for each one, either

  * uses the real implementation if it exists on the running system,
  * or supplies a genuine Windows 7 implementation (win7shim_fallback.c),
  * or falls back to `xor eax,eax; ret` so the DLL always loads.

Usage:
    python3 gen_shim.py imports.txt [--outdir .] [--dllname w7shim]

`imports.txt` holds one line per DLL:  <dll> <func> <func> ...
"""

import argparse
import os
import sys

# Additional modules probed when a name is absent from its canonical DLL.
EXTRA_MODULES = {
    "KERNEL32.dll": ("ntdll.dll",),
    "api-ms-win-core-path-l1-1-0.dll": ("shcore.dll", "shlwapi.dll"),
    "dxgi.dll": ("d3d11.dll",),
}

# Alternative spellings of the same function in the fallback modules.
ALIASES = {
    "EncodePointer": ("RtlEncodePointer",),
    "DecodePointer": ("RtlDecodePointer",),
    "FlsAlloc": ("RtlFlsAlloc",),
    "FlsFree": ("RtlFlsFree",),
    "FlsGetValue": ("RtlFlsGetValue",),
    "FlsSetValue": ("RtlFlsSetValue",),
}

MAX_MODULES = 3
MAX_NAMES = 4


def read_imports(path):
    """Parse '<dll> <func> <func>' lines into [(dll, func)], order preserved."""
    out, seen = [], set()
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            dll = parts[0]
            for fn in parts[1:]:
                if (dll, fn) not in seen:
                    seen.add((dll, fn))
                    out.append((dll, fn))
    return out


def mangle(name):
    """Turn a Win32 function name into a symbol-safe identifier fragment."""
    return "".join(c if c.isalnum() else "_" for c in name)


def _cstr(value):
    return '"%s"' % value if value else "NULL"

def gen_table_c(entries, path):
    """Resolver table plus the FARPROC slot array filled in by DllMain."""
    out = [
        "/* Generated by gen_shim.py - do not edit by hand. */",
        '#include "win7shim.h"',
        "",
        "const struct win7shim_entry win7shim_table[] = {",
    ]
    for dll, fn in entries:
        mods = list(EXTRA_MODULES.get(dll, ()))[:MAX_MODULES]
        mods += [None] * (MAX_MODULES - len(mods))
        names = [fn] + list(ALIASES.get(fn, ()))
        names = names[:MAX_NAMES] + [None] * (MAX_NAMES - len(names))
        out.append(
            "    {%s, {%s, %s, %s}, {%s, %s, %s, %s}},"
            % (_cstr(dll),
               _cstr(mods[0]), _cstr(mods[1]), _cstr(mods[2]),
               _cstr(names[0]), _cstr(names[1]), _cstr(names[2]), _cstr(names[3]))
        )
    out.append("};")
    out.append("")
    out.append("const int win7shim_table_size = %d;" % len(entries))
    out.append("")
    out.append("/* Resolved at DLL_PROCESS_ATTACH; index matches win7shim_table. */")
    out.append("FARPROC win7shim_slots[%d];" % max(len(entries), 1))
    out.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))


def gen_thunks(entries, path):
    """One 6-byte RIP-relative indirect jump per exported function.

    win7shim_slots is a plain array, so each slot's offset is known at
    generation time and can be encoded directly into the instruction.
    """
    out = [
        "/* Generated by gen_shim.py - do not edit by hand. */",
        "        .code64",
        "",
        "/* Last resort when there is neither a real API nor a fallback. */",
        "        .globl  win7shim_stub_missing",
        "win7shim_stub_missing:",
        "        xor     %eax, %eax",
        "        ret",
        "",
    ]
    for i, (dll, fn) in enumerate(entries):
        out += [
            "        .globl  win7shim_stub_%s" % mangle(fn),
            "win7shim_stub_%s:" % mangle(fn),
            "        jmp     *win7shim_slots+%d(%%rip)" % (i * 8),
            "",
        ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))


def gen_def(entries, path, dllname):
    """Module definition file: one exported symbol per thunk."""
    out = [
        "; Generated by gen_shim.py - do not edit by hand.",
        "; Every redirected import becomes an export of the shim.",
        "LIBRARY %s" % dllname,
        "EXPORTS",
    ]
    for dll, fn in entries:
        out.append("    %s = win7shim_stub_%s" % (fn, mangle(fn)))
    out += [
        "    win7shim_stub_missing = win7shim_stub_missing",
        # Test hook: lets the self-test call a Windows 7 implementation directly
        # instead of the thunk, which may forward to the host's own export.
        "    win7shim_get_fallback = win7shim_get_fallback",
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("imports", help="file listing '<dll> <func>...' per line")
    ap.add_argument("--outdir", default=".")
    ap.add_argument("--dllname", default="w7shim")
    args = ap.parse_args()

    entries = read_imports(args.imports)
    if not entries:
        print("no imports found in %s" % args.imports, file=sys.stderr)
        return 1

    os.makedirs(args.outdir, exist_ok=True)
    gen_table_c(entries, os.path.join(args.outdir, "win7shim_table.c"))
    gen_thunks(entries, os.path.join(args.outdir, "win7shim_thunks.S"))
    gen_def(entries, os.path.join(args.outdir, "win7shim.def"), args.dllname)

    print("generated shim surface for %d functions" % len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main())
