/*
 * win7shim.dll - lets Windows 7 load sherpa-onnx binaries that were built with
 * a Windows 10 SDK / VS2022 toolchain.
 *
 * The stock sherpa-onnx-win-x64 binaries statically import a handful of
 * functions that only exist on Windows 8+ (GetSystemTimePreciseAsFileTime,
 * CreateFile2, InitializeCriticalSectionEx, GetProcessMitigationPolicy, the
 * FLS/condition-variable family, PathCch*, CreateDXGIFactory2).  On Windows 7
 * the loader fails immediately with
 *
 *     "The procedure entry point ... could not be located in the dynamic
 *      library KERNEL32.dll"
 *
 * and the process never starts.  There is no way to add a function to the real
 * KERNEL32.dll, so the only fix is to redirect those imports somewhere else.
 *
 * Design: every redirected import becomes a 6-byte trampoline
 *
 *       stub_NAME:  jmp qword ptr [slot_NAME(%rip)]
 *
 * and at DLL_PROCESS_ATTACH time each slot is filled with the address of the
 * real function, located with GetProcAddress over a list of candidate modules
 * (the canonical DLL first, then ntdll.dll / kernel32.dll).  If a function
 * cannot be found anywhere we point the slot at a `return 0` stub, so the DLL
 * always loads - the worst case is a feature returning a null/false result
 * instead of a hard failure at process start.
 *
 * A handful of functions get real Win32 7 implementations in
 * win7shim_fallback.c.
 */

#include <windows.h>
#include "win7shim.h"

/* Generated by gen_shim.py - one thunk per redirected import. */
extern void win7shim_stub_missing(void);

struct win7shim_sys win7shim_sys = {NULL, NULL, NULL};

/*
 * Try every name spelling against every candidate module: first the DLL the
 * import came from, then the entry's fallback modules, then the always-present
 * ntdll / kernel32.  Falling through to ntdll is what lets EncodePointer and
 * friends (ntdll exports them as RtlEncodePointer) resolve on Windows 7.
 */
static int win7shim_resolve(const struct win7shim_entry *e, FARPROC *out) {
    /* Last two probes are universal: ntdll and kernel32 are always loaded. */
    const char *dlls[5];
    int ndll = 0, n, m;

    dlls[ndll++] = e->primary;
    for (m = 0; m < 3 && e->modules[m]; ++m) dlls[ndll++] = e->modules[m];
    dlls[ndll++] = "ntdll.dll";
    dlls[ndll++] = "kernel32.dll";

    for (n = 0; n < 4 && e->names[n]; ++n) {
        for (m = 0; m < ndll; ++m) {
            HMODULE h = win7shim_sys.gmha(dlls[m]);
            FARPROC p;
            if (!h) continue;
            p = win7shim_sys.gpa(h, e->names[n]);
            if (p) {
                *out = p;
                return 1;
            }
        }
    }
    return 0;
}

/* Symbols that, if unresolved, must abort: process can't run without them. */
static const char *const kRequired[] = {
    "GetProcAddress", "LoadLibraryA", "GetModuleHandleA", "GetModuleHandleW",
    "GetLastError", "SetLastError", "VirtualAlloc", "VirtualFree", "HeapAlloc",
    "HeapFree", "GetProcessHeap", "CreateFileW", "WriteFile", "CloseHandle",
    NULL,
};

static int win7shim_is_required(const char *name) {
    int i;
    for (i = 0; kRequired[i]; ++i) {
        if (win7shim_sys.lstrcmp(kRequired[i], name) == 0) return 1;
    }
    return 0;
}


BOOL WINAPI DllMain(HINSTANCE self, DWORD reason, LPVOID reserved) {
    int i;
    (void)self;
    (void)reserved;

    if (reason != DLL_PROCESS_ATTACH) return TRUE;

    /*
     * Everything below (win7shim_resolve, lstrcmpA, ...) runs code that may
     * itself be imported from win7shim, so bootstrap the three primitives we
     * need straight from the real KERNEL32.dll to avoid infinite recursion.
     *
     * These three direct calls are safe: they are linked against the real
     * KERNEL32.dll because we never redirect the shim's own import table.
     */
    {
        HMODULE k32 = GetModuleHandleA("kernel32.dll");
        HMODULE(WINAPI *gmha)(LPCSTR);
        FARPROC(WINAPI *gpa)(HMODULE, LPCSTR);
        int(WINAPI *lstrcmpA_)(LPCSTR, LPCSTR);

        if (!k32) return FALSE;
        gmha = (HMODULE(WINAPI *)(LPCSTR))GetProcAddress(k32, "GetModuleHandleA");
        gpa = (FARPROC(WINAPI *)(HMODULE, LPCSTR))GetProcAddress(k32, "GetProcAddress");
        lstrcmpA_ = (int(WINAPI *)(LPCSTR, LPCSTR))GetProcAddress(k32, "lstrcmpA");
        if (!gmha || !gpa || !lstrcmpA_) return FALSE;

        win7shim_sys.gmha = gmha;
        win7shim_sys.gpa = gpa;
        win7shim_sys.lstrcmp = lstrcmpA_;
    }

    for (i = 0; i < win7shim_table_size; ++i) {
        FARPROC p = NULL;
        if (!win7shim_resolve(&win7shim_table[i], &p)) {
            p = win7shim_get_fallback(win7shim_table[i].names[0]);
        }
        if (!p) {
            if (win7shim_is_required(win7shim_table[i].names[0])) return FALSE;
            p = (FARPROC)win7shim_stub_missing;
        }
        win7shim_slots[i] = p;
    }

    return TRUE;
}